import { EWSNode, PestTrapNode, AlarmLog, UserAccount } from './types';

export const INITIAL_USERS: UserAccount[] = [
  {
    id: 'user-01',
    username: 'admin_bpbd',
    fullName: 'Ir. Hendra Wijaya, M.T.',
    role: 'superadmin',
    department: 'Pusdalops BPBD & Tim Gabungan Mitigasi',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-02',
    username: 'operator_ews1',
    fullName: 'Budi Santoso (Pos Pantau 1)',
    role: 'operator_ews1',
    assignedEwsId: 'EWS-01',
    department: 'Pos Pantau Sektor Utara - Lereng Pasir Madu',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-03',
    username: 'operator_ews2',
    fullName: 'Rian Pratama (Pos Pantau 2)',
    role: 'operator_ews2',
    assignedEwsId: 'EWS-02',
    department: 'Pos Pantau Sektor Barat - Tebing Cikadu',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-04',
    username: 'operator_ews3',
    fullName: 'Ahmad Fauzi (Pos Pantau 3)',
    role: 'operator_ews3',
    assignedEwsId: 'EWS-03',
    department: 'Pos Pantau Sektor Timur - Jalur Aliran Talaga',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-05',
    username: 'operator_ews4',
    fullName: 'Agus Setiawan (Pos Pantau 4)',
    role: 'operator_ews4',
    assignedEwsId: 'EWS-04',
    department: 'Pos Pantau Sektor Selatan - Pemukiman Warga',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'user-06',
    username: 'warga_publik',
    fullName: 'Akses Portal Terbuka Komunitas',
    role: 'public',
    department: 'Warga Masyarakat & Relawan Desa',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
  }
];

export const INITIAL_EWS_NODES: EWSNode[] = [];

export const PRESET_EWS_NODES: EWSNode[] = [
  {
    id: 'EWS-01',
    name: 'EWS 01 - Lereng Pasir Madu',
    location: 'Sektor Lereng Utara (KM 14.2) - Lereng Atas Rawan Longsor',
    coordinates: { lat: -6.8924, lng: 107.6183 },
    status: 'aman',
    sirenActive: false,
    stroboActive: false,
    muted: false,
    sensorData: {
      pitchAngle: 0.0,
      rollAngle: 0.0,
      soilMoisture: 0.0,
      soilTemperature: 0.0,
      rainfallRate: 0.0,
      rainfallCumulative: 0.0,
      vibrationLevel: 0.0,
      batteryVoltage: 0.0,
      batteryCurrent: 0,
      solarCurrent: 0,
      gsmSignalDbm: 0,
      gsmStatus: 'offline',
      microSdStorageUsedMb: 0,
      microSdStorageTotalMb: 30400,
      firmwareVersion: 'v2.4.1-ESP32-A7670C',
      uptimeHours: 0,
      lastUpdated: 'Menunggu transmisi WebSocket...',
    },
    telegramConfig: {
      ewsId: 'EWS-01',
      botToken: '6892348121:AAHq_7xL98Kz2w_PasirMaduBot',
      chatId: '-1001928374650',
      channelName: 'Grup Relawan & Warga Lereng Pasir Madu',
      enabled: true,
      notifySiaga: true,
      notifyBahaya: true,
      notifyOffline: true,
      notifyBateraiLemah: true,
      notifySensorGagal: true,
      notifyNormalKembali: true,
      dailyReport: true,
      lastTestStatus: 'idle',
      lastTestTime: '-',
    },
    thresholds: {
      tiltWarning: 1.5,
      tiltDanger: 3.0,
      rainWarning: 20.0,
      rainDanger: 50.0,
      soilMoistureWarning: 75.0,
      vibrationDanger: 0.25,
      batteryLowVoltage: 11.8,
    },
  },
  {
    id: 'EWS-02',
    name: 'EWS 02 - Tebing Cikadu',
    location: 'Sektor Barat Tebing Cikadu - Lereng Curam Batuan Vulkanik',
    coordinates: { lat: -6.8978, lng: 107.6145 },
    status: 'aman',
    sirenActive: false,
    stroboActive: false,
    muted: false,
    sensorData: {
      pitchAngle: 0.0,
      rollAngle: 0.0,
      soilMoisture: 0.0,
      soilTemperature: 0.0,
      rainfallRate: 0.0,
      rainfallCumulative: 0.0,
      vibrationLevel: 0.0,
      batteryVoltage: 0.0,
      batteryCurrent: 0,
      solarCurrent: 0,
      gsmSignalDbm: 0,
      gsmStatus: 'offline',
      microSdStorageUsedMb: 0,
      microSdStorageTotalMb: 30400,
      firmwareVersion: 'v2.4.1-ESP32-A7670C',
      uptimeHours: 0,
      lastUpdated: 'Menunggu transmisi WebSocket...',
    },
    telegramConfig: {
      ewsId: 'EWS-02',
      botToken: '7109283419:BBKk_8wN42Pt9m_TebingCikaduBot',
      chatId: '-1002847591023',
      channelName: 'Komando Lapangan Tebing Cikadu',
      enabled: true,
      notifySiaga: true,
      notifyBahaya: true,
      notifyOffline: true,
      notifyBateraiLemah: true,
      notifySensorGagal: true,
      notifyNormalKembali: true,
      dailyReport: false,
      lastTestStatus: 'idle',
      lastTestTime: '-',
    },
    thresholds: {
      tiltWarning: 1.5,
      tiltDanger: 3.0,
      rainWarning: 20.0,
      rainDanger: 50.0,
      soilMoistureWarning: 75.0,
      vibrationDanger: 0.25,
      batteryLowVoltage: 11.8,
    },
  },
  {
    id: 'EWS-03',
    name: 'EWS 03 - Jalur Aliran Talaga',
    location: 'Sektor Lembah Aliran Air Talaga - Rawan Debris & Banjir Bandang',
    coordinates: { lat: -6.9031, lng: 107.6210 },
    status: 'aman',
    sirenActive: false,
    stroboActive: false,
    muted: false,
    sensorData: {
      pitchAngle: 0.0,
      rollAngle: 0.0,
      soilMoisture: 0.0,
      soilTemperature: 0.0,
      rainfallRate: 0.0,
      rainfallCumulative: 0.0,
      vibrationLevel: 0.0,
      batteryVoltage: 0.0,
      batteryCurrent: 0,
      solarCurrent: 0,
      gsmSignalDbm: 0,
      gsmStatus: 'offline',
      microSdStorageUsedMb: 0,
      microSdStorageTotalMb: 30400,
      firmwareVersion: 'v2.4.1-ESP32-A7670C',
      uptimeHours: 0,
      lastUpdated: 'Menunggu transmisi WebSocket...',
    },
    telegramConfig: {
      ewsId: 'EWS-03',
      botToken: '7482910321:CCDd_1uM84Xq3z_TalagaStreamBot',
      chatId: '-1003928174567',
      channelName: 'Grup Pantau Debris & Banjir Talaga',
      enabled: true,
      notifySiaga: true,
      notifyBahaya: true,
      notifyOffline: true,
      notifyBateraiLemah: true,
      notifySensorGagal: true,
      notifyNormalKembali: true,
      dailyReport: true,
      lastTestStatus: 'idle',
      lastTestTime: '-',
    },
    thresholds: {
      tiltWarning: 1.5,
      tiltDanger: 3.0,
      rainWarning: 20.0,
      rainDanger: 50.0,
      soilMoistureWarning: 75.0,
      vibrationDanger: 0.25,
      batteryLowVoltage: 11.8,
    },
  },
  {
    id: 'EWS-04',
    name: 'EWS 04 - Akses Pemukiman Sukamulya',
    location: 'Sektor Selatan Jalan Utama & Pemukiman - Kaki Lereng',
    coordinates: { lat: -6.9085, lng: 107.6242 },
    status: 'aman',
    sirenActive: false,
    stroboActive: false,
    muted: false,
    sensorData: {
      pitchAngle: 0.0,
      rollAngle: 0.0,
      soilMoisture: 0.0,
      soilTemperature: 0.0,
      rainfallRate: 0.0,
      rainfallCumulative: 0.0,
      vibrationLevel: 0.0,
      batteryVoltage: 0.0,
      batteryCurrent: 0,
      solarCurrent: 0,
      gsmSignalDbm: 0,
      gsmStatus: 'offline',
      microSdStorageUsedMb: 0,
      microSdStorageTotalMb: 30400,
      firmwareVersion: 'v2.4.1-ESP32-A7670C',
      uptimeHours: 0,
      lastUpdated: 'Menunggu transmisi WebSocket...',
    },
    telegramConfig: {
      ewsId: 'EWS-04',
      botToken: '7920192834:EEFf_5kP67Za1s_SukamulyaAlertBot',
      chatId: '-1004829104821',
      channelName: 'Warga Siaga Bencana Sukamulya',
      enabled: true,
      notifySiaga: true,
      notifyBahaya: true,
      notifyOffline: true,
      notifyBateraiLemah: true,
      notifySensorGagal: true,
      notifyNormalKembali: true,
      dailyReport: true,
      lastTestStatus: 'idle',
      lastTestTime: '-',
    },
    thresholds: {
      tiltWarning: 1.5,
      tiltDanger: 3.0,
      rainWarning: 20.0,
      rainDanger: 50.0,
      soilMoistureWarning: 75.0,
      vibrationDanger: 0.25,
      batteryLowVoltage: 11.8,
    },
  },
];

export const INITIAL_PEST_TRAPS: PestTrapNode[] = [
  {
    id: 'TRAP-01',
    name: 'Perangkap Hama 01 - Kebun Kopi Lereng Atas',
    location: 'Area Perkebunan Warga Blok A (Elevasi 1,120 mdpl)',
    uvLedStatus: false,
    blowerStatus: false,
    pirTriggerCount: 0,
    photoelectricCount: 0,
    containerCapacityPercent: 0,
    batteryVoltage: 0.0,
    solarChargingCurrent: 0,
    mode: 'standby',
    status: 'standby',
  },
  {
    id: 'TRAP-02',
    name: 'Perangkap Hama 02 - Kebun Sayur Holtikultura',
    location: 'Lahan Cabai & Kubis Blok B (Elevasi 1,050 mdpl)',
    uvLedStatus: false,
    blowerStatus: false,
    pirTriggerCount: 0,
    photoelectricCount: 0,
    containerCapacityPercent: 0,
    batteryVoltage: 0.0,
    solarChargingCurrent: 0,
    mode: 'standby',
    status: 'standby',
  },
  {
    id: 'TRAP-03',
    name: 'Perangkap Hama 03 - Pematang Padi Sawah Terasering',
    location: 'Sawah Blok C Pasir Cikadu (Elevasi 980 mdpl)',
    uvLedStatus: false,
    blowerStatus: false,
    pirTriggerCount: 0,
    photoelectricCount: 0,
    containerCapacityPercent: 0,
    batteryVoltage: 0.0,
    solarChargingCurrent: 0,
    mode: 'standby',
    status: 'standby',
  },
  {
    id: 'TRAP-04',
    name: 'Perangkap Hama 04 - Kebun Buah & Sengon',
    location: 'Zona Penyangga Hutan Rakyat Blok D',
    uvLedStatus: false,
    blowerStatus: false,
    pirTriggerCount: 0,
    photoelectricCount: 0,
    containerCapacityPercent: 0,
    batteryVoltage: 0.0,
    solarChargingCurrent: 0,
    mode: 'standby',
    status: 'standby',
  },
  {
    id: 'TRAP-05',
    name: 'Perangkap Hama 05 - Bibit Tanaman Vetiver & Bambu',
    location: 'Zona Penguat Tebing Kritis Blok E',
    uvLedStatus: false,
    blowerStatus: false,
    pirTriggerCount: 0,
    photoelectricCount: 0,
    containerCapacityPercent: 0,
    batteryVoltage: 0.0,
    solarChargingCurrent: 0,
    mode: 'standby',
    status: 'standby',
  },
];

export const INITIAL_ALARM_LOGS: AlarmLog[] = [];

